name: onestore_app
description: Online store app project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  awesome_dialog: ^3.2.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_native_splash: ^2.4.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  http: ^1.2.1
  hydrated_bloc: ^9.1.5
  money_formatter: ^0.0.5
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  webview_flutter: ^4.7.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 600
